### ISSUE TITLE
buffers - error introduced

### ISSUE THREAD

**Issue by wwaites** [paracrawl/b64filter#2]
The change ported from /paracrawl/b64map/1 caused the `readNLines` function to fail because the underlying buffer will return `io.EOF` if it is full. `readNLines` sensibly takes this to mean there is no more data to read but that is not, in fact, the right thing to do. Masked this for now by simply not treating `io.EOF` as an error which will be a problem if the command being wrapped does not, in fact, produce enough lines.

**Comment by wwaites** [comment]
Use of bytes.Buffer directly is not thread safe. After some time running, we see nonsense like this:

    panic: runtime error: slice bounds out of range [1024:512]

    goroutine 240 [running]:
    bytes.(*Buffer).readSlice(0xc0002f21b0, 0xc00139c00a, 0x400, 0x0, 0x400, 0xc00139c000, 0x0)
            /usr/lib/golang/src/bytes/buffer.go:418 +0x10d
    bytes.(*Buffer).ReadBytes(...)
            /usr/lib/golang/src/bytes/buffer.go:409
    main.readNLines(0x4, 0xc0002f21b0, 0xc000c84000, 0x1, 0x1, 0x0, 0x0)
            /home/cs-wait1/go/src/github.com/paracrawl/b64filter/b64filter.go:105 +0x124
    main.writeDocs(0xc0002ec140, 0xc0002ee120, 0xc0002f21b0, 0x51de40, 0xc000312008)
            /home/cs-wait1/go/src/github.com/paracrawl/b64filter/b64filter.go:149 +0x10c
    created by main.main
            /home/cs-wait1/go/src/github.com/paracrawl/b64filter/b64filter.go:210 +0x38c
